version: "4"
services:

  # this container will run Cypress test using Chrome browser
  e2e-chrome:
    image: "cypress-w3org"
    command: "test:chrome"
    volumes:
      - ./dockerReportsChrome:/cypress-docker/cypress/reports-chrome/
      - ./dockerReportsChrome/screenshots:/cypress-docker/cypress/screenshots/

  # this container will run Cypress test using Firefox browser
  # note that both Chrome and Firefox browsers were pre-installed in the Docker image
  e2e-firefox:
    image: "cypress-w3org"
    command: "test:firefox"
    # if you want to debug FF run, pass DEBUG variable like
    environment:
      - DEBUG=cypress:server:browsers:firefox-util,cypress:server:util:process_profiler
    volumes:
      - ./dockerReportsFirefox:/cypress-docker/cypress/reports-firefox/